apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-role
  namespace: fleet-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
  namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: manager-role
  namespace: manager-role-namespace

